darknet3d_node:
  ros__parameters:
    darknet_ros_topic: /image_detection/bounding_boxes
    output_bbx3d_topic: /sensor_fusion/bounding_boxes
    output_markers_topic: /sensor_fusion/markers
    output_view_points_topic: /sensor_fusion/view_points
    output_human_points_topic: /sensor_fusion/human_points
    point_cloud_topic: /rear_velodyne/points
    camera_info_topic: /rear_camera/color/camera_info
    camera_image_topic: /image_detection/detection_image
    raw_camera_topic: /rear_camera/color/image_raw
    bbx3d_tolerance: 0.4
    working_frame: rear_camera_link
    transform_frame: base_footprint
    ground_detection_threshold: 0.5
    minimum_probability: 0.4
    interested_classes: ["person"]
